
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dell
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    int turn=2;
    int buttonused[]={0,0,0,0,0,0,0,0,0};
    int pXwon[]={0,0,0,0,0,0,0,0,0};
    int pOwon[]={0,0,0,0,0,0,0,0,0};
    private int i;
    
    int pXwon()
    {
        if (pXwon[0]==1 && pXwon[1]==1 && pXwon[2]==1)
        {
            return 1;
        }
         if (pXwon[3]==1 && pXwon[4]==1 && pXwon[5]==1)
        {
            return 1;
        }
          if (pXwon[6]==1 && pXwon[7]==1 && pXwon[8]==1)
        {
            return 1;
        }
           if (pXwon[0]==1 && pXwon[3]==1 && pXwon[6]==1)
        {
            return 1;
        }
            if (pXwon[1]==1 && pXwon[4]==1 && pXwon[7]==1)
        {
            return 1;
        }
             if (pXwon[2]==1 && pXwon[5]==1 && pXwon[8]==1)
        {
            return 1;
        }
              if (pXwon[0]==1 && pXwon[4]==1 && pXwon[8]==1)
        {
            return 1;
        }
               if (pXwon[2]==1 && pXwon[4]==1 && pXwon[6]==1)
        {
            return 1;
        }
                           
        return 0;
    }
    
    int pOwon()
    {
        if (pOwon[0]==1 && pOwon[1]==1 && pOwon[2]==1)
        {
            return 1;
        }
         if (pOwon[3]==1 && pOwon[4]==1 && pOwon[5]==1)
        {
            return 1;
        }
          if (pOwon[6]==1 && pOwon[7]==1 && pOwon[8]==1)
        {
            return 1;
        }
           if (pOwon[0]==1 && pOwon[3]==1 && pOwon[6]==1)
        {
            return 1;
        }
            if (pOwon[1]==1 && pOwon[4]==1 && pOwon[7]==1)
        {
            return 1;
        }
             if (pOwon[2]==1 && pOwon[5]==1 && pOwon[8]==1)
        {
            return 1;
        }
              if (pOwon[0]==1 && pOwon[4]==1 && pOwon[8]==1)
        {
            return 1;
        }
               if (pOwon[2]==1 && pOwon[4]==1 && pOwon[6]==1)
        {
            return 1;
        }
                           
        return 0;
    }
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        b0 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 51, 51));
        reset.setText("PLAY AGAIN!!!");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Simplified Arabic Fixed", 3, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("LET'S PLAY !!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
      if(buttonused[0]==0){
        if(turn%2==0){
            turn++;
            b0.setText("X");
            buttonused[0]=1;
            pXwon[0]=1;
            int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        else
        {
            turn++;
            b0.setText("0");
            buttonused[0]=1;
            pOwon[0]=1;
             int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        }
        else
        {
             JOptionPane.showMessageDialog(rootPane,"This box is used!!!!");
                }
        
    }                                  

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        if(buttonused[1]==0){
        if(turn%2==0){
            turn++;
            b1.setText("X");
            buttonused[1]=1;
            pXwon[1]=1;
            int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        else
        {
            turn++;
            b1.setText("0");
            buttonused[1]=1;
            pOwon[1]=1;
             int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        }
        else
        {
             JOptionPane.showMessageDialog(rootPane,"This box is used!!!!");
                }
    }                                  

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
        if(buttonused[2]==0){
        if(turn%2==0){
            turn++;
            b2.setText("X");
            buttonused[2]=1;
            pXwon[2]=1;
            int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        else
        {
            turn++;
            b2.setText("0");
            buttonused[2]=1;
            pOwon[2]=1;
             int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        }
        else
        {
             JOptionPane.showMessageDialog(rootPane,"This box is used!!!!");
                }
    }                                  

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
         if(buttonused[6]==0){
        if(turn%2==0){
            turn++;
            b6.setText("X");
            buttonused[6]=1;
            pXwon[6]=1;
            int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        else
        {
            turn++;
            b6.setText("0");
            buttonused[6]=1;
            pOwon[6]=1;
             int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        }
        else
        {
             JOptionPane.showMessageDialog(rootPane,"This box is used!!!!");
                }
    }                                  

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
         if(buttonused[4]==0){
        if(turn%2==0){
            turn++;
            b4.setText("X");
            buttonused[4]=1;
            pXwon[4]=1;
            int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        else
        {
            turn++;
            b4.setText("0");
            buttonused[4]=1;
            pOwon[4]=1;
             int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        }
        else
        {
             JOptionPane.showMessageDialog(rootPane,"This box is used!!!!");
                }
    }                                  

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
         if(buttonused[5]==0){
        if(turn%2==0){
            turn++;
            b5.setText("X");
            buttonused[5]=1;
            pXwon[5]=1;
            int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        else
        {
            turn++;
            b5.setText("0");
            buttonused[5]=1;
            pOwon[5]=1;
             int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        }
        else
        {
             JOptionPane.showMessageDialog(rootPane,"This box is used!!!!");
                }
    }                                  

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
         if(buttonused[3]==0){
        if(turn%2==0){
            turn++;
            b3.setText("X");
            buttonused[3]=1;
            pXwon[3]=1;
            int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        else
        {
            turn++;
            b3.setText("0");
            buttonused[3]=1;
            pOwon[3]=1;
             int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        }
        else
        {
             JOptionPane.showMessageDialog(rootPane,"This box is used!!!!");
                }
    }                                  

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
         if(buttonused[7]==0){
        if(turn%2==0){
            turn++;
            b7.setText("X");
            buttonused[7]=1;
            pXwon[7]=1;
            int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        else
        {
            turn++;
            b7.setText("0");
            buttonused[7]=1;
            pOwon[7]=1;
             int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        }
        else
        {
             JOptionPane.showMessageDialog(rootPane,"This box is used!!!!");
                }
    }                                  

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
         if(buttonused[8]==0){
        if(turn%2==0){
            turn++;
            b8.setText("X");
            buttonused[8]=1;
            pXwon[8]=1;
            int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        else
        {
            turn++;
            b8.setText("0");
            buttonused[8]=1;
            pOwon[8]=1;
             int result1=pXwon();
            int result2=pOwon();
            
            if(result1==1){
                JOptionPane.showMessageDialog(rootPane,"Player X won!!!");
            }
            else if (result2==1){
                JOptionPane.showMessageDialog(rootPane, "Player O won!!!");
            }
        }
        }
        else
        {
             JOptionPane.showMessageDialog(rootPane,"This box is used!!!!");
                }
    }                                  

    @SuppressWarnings("empty-statement")
    private void resetActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        b0.setText("");
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        
        turn=2;
        for(int i=0;i<9;i++);
        {
            buttonused[i]=0;
        }
        for(int i=0;i<9;i++);
        {
            pXwon[i]=0;
        }
        for(int i=0;i<9;i++);
        {
            pOwon[i]=0;
        }
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reset;
    // End of variables declaration                   
}